
name: Daily snapshot

on:
  schedule:
    - cron:  '0 22 * * *'

jobs:
  createTag:
    name: Generate a new tag and push it
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1.2.0
      - name: create tag
        run: |
          git config --global user.name 'GitHubActions'
          git config --global user.email 'GitHubActions@users.noreply.github.com'
          git remote set-url origin https://x-access-token:${{ secrets.REPO_SCOPED_TOKEN }}@github.com/${{ github.repository }}
          python ./ci/tag.py
          git push origin --tags  